route:
    group_by: ["alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 6h
    receiver: "gmail"
receivers:
    - name: "web.hook"
      webhook_configs:
          - url: "http://127.0.0.1:5001/"
    - name: "gmail"
      email_configs:
          - to: "james.alertmanager@gmail.com"
            from: "james.alertmanager@gmail.com"
            smarthost: smtp.gmail.com:587
            auth_username: "james.alertmanager@gmail.com"
            auth_identity: "james.alertmanager@gmail.com"
            auth_password: "tbfvanwlxytmvcwr"
inhibit_rules:
    - source_match:
          severity: "critical"
      target_match:
          severity: "warning"
      equal: ["alertname", "dev", "instance"]
